using DinamikCRM.DinamikCRM.Entity.Models.DB;
using System;
using System.Collections.Generic;
using System.Text;

namespace DinamikCRM.Entity.Models.DB
{
    public partial class TblAccount : BaseEntity { }
    public partial class TblAccountCurrent : BaseEntity { }
    public partial class TblAccountTransaction : BaseEntity { }
    public partial class TblActivity : BaseEntity { }
    public partial class TblActivityCustomFieldData : BaseEntity { }
    public partial class TblActivityHistory : BaseEntity { }
    public partial class TblActivityLog : BaseEntity { }
    public partial class TblAppointment : BaseEntity { }
    public partial class TblAppointmentCustomFieldData : BaseEntity { }
    public partial class TblAppointmentDetail : BaseEntity { }
    public partial class TblAttach : BaseEntity { }
    public partial class TblBoard : BaseEntity { }
    public partial class TblBoardCategory : BaseEntity { }
    public partial class TblBoardItem : BaseEntity { }
    public partial class TblBrand : BaseEntity { }
    public partial class TblBundle : BaseEntity { }
    public partial class TblBundleDetail : BaseEntity { }
    public partial class TblCalendar : BaseEntity { }
    public partial class TblCall : BaseEntity { }
    public partial class TblCallList : BaseEntity { }
    public partial class TblCallListData : BaseEntity { }
    public partial class TblCallScheduler : BaseEntity { }
    public partial class TblCallScript : BaseEntity { }
    public partial class TblCampaignList : BaseEntity { }
    public partial class TblCampaignTempList : BaseEntity { }
    public partial class TblCategory : BaseEntity { }
    public partial class TblChat : BaseEntity { }
    public partial class TblChatRoom : BaseEntity { }
    public partial class TblChatRoomMember : BaseEntity { }
    public partial class TblCheckIn : BaseEntity { }
    public partial class TblCity : BaseEntity { }
    public partial class TblCompany : BaseEntity { }
    public partial class TblCompanyAddress : BaseEntity { }
    public partial class TblCompanyBranch : BaseEntity { }
    public partial class TblCompanyCategory : BaseEntity { }
    public partial class TblCompanyContact : BaseEntity { }
    public partial class TblCompanyCustomFieldData : BaseEntity { }
    public partial class TblCompanyDetail : BaseEntity { }
    public partial class TblCompanyEmail : BaseEntity { }
    public partial class TblCompanyPermit : BaseEntity { }
    public partial class TblCompanyPhone : BaseEntity { }
    public partial class TblCompanySettings : BaseEntity { }
    public partial class TblCompanySocial : BaseEntity { }
    public partial class TblContact : BaseEntity { }
    public partial class TblContactAddress : BaseEntity { }
    public partial class TblContactContact : BaseEntity { }
    public partial class TblContactCustomFieldData : BaseEntity { }
    public partial class TblContactDetail : BaseEntity { }
    public partial class TblContactEmail : BaseEntity { }
    public partial class TblContactEmotion : BaseEntity { }
    public partial class TblContactForm : BaseEntity { }
    public partial class TblContactPermit : BaseEntity { }
    public partial class TblContactPhone : BaseEntity { }
    public partial class TblContactSettings : BaseEntity { }
    public partial class TblContactSocial : BaseEntity { }
    public partial class TblContent : BaseEntity { }
    public partial class TblContentCategory : BaseEntity { }
    public partial class TblContentComment : BaseEntity { }
    public partial class TblContentReact : BaseEntity { }
    public partial class TblCountry : BaseEntity { }
    public partial class TblCoupon : BaseEntity { }
    public partial class TblCouponData : BaseEntity { }
    public partial class TblCustomField : BaseEntity { }
    public partial class TblCustomer : BaseEntity {    }
    public partial class TblCustomerAddress : BaseEntity { }
    public partial class TblCustomerContact : BaseEntity { }
    public partial class TblCustomerCustomFieldData : BaseEntity { }
    public partial class TblCustomerDetail : BaseEntity { }
    public partial class TblCustomerEmail : BaseEntity { }
    public partial class TblCustomerEmotion : BaseEntity { }
    public partial class TblCustomerPermit : BaseEntity { }
    public partial class TblCustomerPhone : BaseEntity { }
    public partial class TblCustomerSettings : BaseEntity { }
    public partial class TblCustomerSocial : BaseEntity { }
    public partial class TblDashboard : BaseEntity { }
    public partial class TblDealer : BaseEntity { }
    public partial class TblDealerAddress : BaseEntity { }
    public partial class TblDealerArea : BaseEntity { }
    public partial class TblDealerEmail : BaseEntity { }
    public partial class TblDealerPhone : BaseEntity { }
    public partial class TblDistrict : BaseEntity { }
    public partial class TblDynamic : BaseEntity { }
    public partial class TblEmailProvider : BaseEntity { }
    public partial class TblEmailSignature : BaseEntity { }
    public partial class TblEmailTemplate : BaseEntity { }
    public partial class TblEmployee : BaseEntity { }
    public partial class TblEmployeeAddress : BaseEntity { }
    public partial class TblEmployeeAsset : BaseEntity { }
    public partial class TblEmployeeCustomFieldData : BaseEntity { }
    public partial class TblEmployeeDetail : BaseEntity { }
    public partial class TblEmployeeEmail : BaseEntity { }
    public partial class TblEmployeeEmotion : BaseEntity { }
    public partial class TblEmployeeLeave : BaseEntity { }
    public partial class TblEmployeeLeaveCategory : BaseEntity { }
    public partial class TblEmployeePhone : BaseEntity { }
    public partial class TblEmployeeSettings : BaseEntity { }
    public partial class TblEmployeeSocial : BaseEntity { }
    public partial class TblExpense : BaseEntity { }
    public partial class TblExpenseCategory : BaseEntity { }
    public partial class TblFaq : BaseEntity { }
    public partial class TblFavorites : BaseEntity { }
    public partial class TblFeed : BaseEntity { }
    public partial class TblFeedComment : BaseEntity { }
    public partial class TblFeedReact : BaseEntity { }
    public partial class TblFeedback : BaseEntity { }
    public partial class TblFeedbackCustomFieldData : BaseEntity { }
    public partial class TblFeedbackHistory : BaseEntity { }
    public partial class TblForm : BaseEntity { }
    public partial class TblFormData : BaseEntity { }
    public partial class TblFormDetail : BaseEntity { }
    public partial class TblGroup : BaseEntity { }
    public partial class TblGroupApi : BaseEntity { }
    public partial class TblGroupBanking : BaseEntity { }
    public partial class TblGroupLanding : BaseEntity { }
    public partial class TblGroupLocation : BaseEntity { }
    public partial class TblGroupSocial : BaseEntity { }
    public partial class TblGroupSolution : BaseEntity { }
    public partial class TblHelp : BaseEntity { }
    public partial class TblImage : BaseEntity { }
    public partial class TblIntegration : BaseEntity { }
    public partial class TblInventory : BaseEntity { }
    public partial class TblInvitation : BaseEntity { }
    public partial class TblLead : BaseEntity { }
    public partial class TblLeadAddress : BaseEntity { }
    public partial class TblLeadContact : BaseEntity { }
    public partial class TblLeadCustomFieldData : BaseEntity { }
    public partial class TblLeadDetail : BaseEntity { }
    public partial class TblLeadEmail : BaseEntity { }
    public partial class TblLeadEmotion : BaseEntity { }
    public partial class TblLeadPermit : BaseEntity { }
    public partial class TblLeadPhone : BaseEntity { }
    public partial class TblLeadSettings : BaseEntity { }
    public partial class TblLeadSocial : BaseEntity { }
    public partial class TblLogEmail : BaseEntity { }
    public partial class TblLogError : BaseEntity { }
    public partial class TblLogLogin : BaseEntity { }
    public partial class TblLogPage : BaseEntity { }
    public partial class TblLogPayment : BaseEntity { }
    public partial class TblLogSearch : BaseEntity { }
    public partial class TblLogSms : BaseEntity { }
    public partial class TblMailbox : BaseEntity { }
    public partial class TblModule : BaseEntity { }
    public partial class TblModuleChangeLog : BaseEntity { }
    public partial class TblModuleDetail : BaseEntity { }
    public partial class TblNeighborhood : BaseEntity { }
    public partial class TblNote : BaseEntity { }
    public partial class TblNoteContent : BaseEntity { }
    public partial class TblNps : BaseEntity { }
    public partial class TblNpsData : BaseEntity { }
    public partial class TblNpsList : BaseEntity { }
    public partial class TblOrder : BaseEntity { }
    public partial class TblOrderDetail : BaseEntity { }
    public partial class TblOrderHistory : BaseEntity { }
    public partial class TblOrderNoteTemplate : BaseEntity { }
    public partial class TblOrderVehicle : BaseEntity { }
    public partial class TblPlan : BaseEntity { }
    public partial class TblProduct : BaseEntity { }
    public partial class TblProductCategory : BaseEntity { }
    public partial class TblProductComment : BaseEntity { }
    public partial class TblProductCustomFieldData : BaseEntity { }
    public partial class TblProductDetail : BaseEntity { }
    public partial class TblProductList : BaseEntity { }
    public partial class TblProductListProduct : BaseEntity { }
    public partial class TblProductVendor : BaseEntity { }
    public partial class TblProject : BaseEntity { }
    public partial class TblProposal : BaseEntity { }
    public partial class TblProposalCategory : BaseEntity { }
    public partial class TblProposalCustomFieldData : BaseEntity { }
    public partial class TblProposalProduct : BaseEntity { }
    public partial class TblProposalService : BaseEntity { }
    public partial class TblProposalSettings : BaseEntity { }
    public partial class TblProposalTemplate : BaseEntity { }
    public partial class TblQuarter : BaseEntity { }
    public partial class TblRelations : BaseEntity { }
    public partial class TblReminder : BaseEntity { }
    public partial class TblRequest : BaseEntity { }
    public partial class TblRequestCategory : BaseEntity { }
    public partial class TblRequestHistory : BaseEntity { }
    public partial class TblRequestLink : BaseEntity { }
    public partial class TblReservation : BaseEntity { }
    public partial class TblReservationCustomFieldData : BaseEntity { }
    public partial class TblRole : BaseEntity { }
    public partial class TblRule : BaseEntity { }
    public partial class TblSales : BaseEntity { }
    public partial class TblSalesCategory : BaseEntity { }
    public partial class TblSalesCustomFieldData : BaseEntity { }
    public partial class TblSalesPayment : BaseEntity { }
    public partial class TblSalesProduct : BaseEntity { }
    public partial class TblSalesService : BaseEntity { }
    public partial class TblSalesShipment : BaseEntity { }
    public partial class TblSector : BaseEntity { }
    public partial class TblSegment : BaseEntity { }
    public partial class TblSeller : BaseEntity { }
    public partial class TblService : BaseEntity { }
    public partial class TblServiceCategory : BaseEntity { }
    public partial class TblServiceDetail : BaseEntity { }
    public partial class TblSettings : BaseEntity { }
    public partial class TblSmsList : BaseEntity { }
    public partial class TblSmsListData : BaseEntity { }
    public partial class TblSmsprovider : BaseEntity { }
    public partial class TblSmstemplate : BaseEntity { }
    public partial class TblStore : BaseEntity { }
    public partial class TblStoreOrder : BaseEntity { }
    public partial class TblSubCategory : BaseEntity { }
    public partial class TblSubscription : BaseEntity { }
    public partial class TblSubscriptionDetail : BaseEntity { }
    public partial class TblSubscriptionPack : BaseEntity { }
    public partial class TblSubscriptionSettings : BaseEntity { }
    public partial class TblSubscriptionTemplate : BaseEntity { }
    public partial class TblSurveyLead : BaseEntity { }
    public partial class TblTag : BaseEntity { }
    public partial class TblTarget : BaseEntity { }
    public partial class TblTask : BaseEntity { }
    public partial class TblTaskCategory : BaseEntity { }
    public partial class TblTaskCustomFieldData : BaseEntity { }
    public partial class TblTaskHistory : BaseEntity { }
    public partial class TblTaskResponsible : BaseEntity { }
    public partial class TblTaskSettings : BaseEntity { }
    public partial class TblTeam : BaseEntity { }
    public partial class TblTransfer : BaseEntity { }
    public partial class TblTransferCustomFieldData : BaseEntity { }
    public partial class TblType : BaseEntity { }
    public partial class TblUrl : BaseEntity { }
    public partial class TblUser : BaseEntity { }
    public partial class TblUserDashboard : BaseEntity { }
    public partial class TblUserDetail : BaseEntity { }
    public partial class TblUserExtension : BaseEntity { }
    public partial class TblUserInvoice : BaseEntity { }
    public partial class TblUserModule : BaseEntity { }
    public partial class TblUserPrivacy : BaseEntity { }
    public partial class TblUserRole : BaseEntity { }
    public partial class TblUserStatus : BaseEntity { }
    public partial class TblUserStatusLog : BaseEntity { }
    public partial class TblUserSubscription : BaseEntity { }
    public partial class TblVehicle : BaseEntity { }
    public partial class TblVendor : BaseEntity { }
    public partial class TblVendorAddress : BaseEntity { }
    public partial class TblVendorBranch : BaseEntity { }
    public partial class TblVendorContact : BaseEntity { }
    public partial class TblVendorCustomFieldData : BaseEntity { }
    public partial class TblVendorEmail : BaseEntity { }
    public partial class TblVendorPhone : BaseEntity { }
}
